import csv

# open Players.csv file with csv.DictReader and read its content into a list of dictionary, players_data
players_data = []
with open('Players.csv', 'r') as f:
    rows = csv.DictReader(f)
    for r in rows:
        players_data.append(r)

# open Teams.csv file with csv.DictReader and read its content into a list of dictionary, teams_data
teams_data = []
with open('Teams.csv', 'r') as f:
    rows = csv.DictReader(f)
    for r in rows:
        teams_data.append(r)


def average_shots(players_data):
    """Returns a tuple with four elements; the first, second, third, and
    fourth elements show the average number of shots made by defenders,
    midfielders, forwards, and goalkeepers, respectively

    Notes: the test results below are printed out with two decimal places to
    get around floating-point errors.

    >>> averages = average_shots(players_data)
    >>> type(averages)
    <class 'tuple'>
    >>> [f'{a:.2f}' for a in averages]
    ['1.16', '2.39', '4.23', '0.03']
    """
    defenders = []
    midfielders = []
    forwards = []
    goalkeepers = []
    for i in range(len(players_data)):
        pos = players_data[i]['position']  # to get position of player
        if pos == 'defender':
            defenders.append(float(players_data[i]['shots']))
        elif pos == 'midfielder':
            midfielders.append(float(players_data[i]['shots']))
        elif pos == 'forward':
            forwards.append(float(players_data[i]['shots']))
        elif pos == 'goalkeeper':
            goalkeepers.append(float(players_data[i]['shots']))
    avg_shot_def = sum(defenders) / len(defenders)
    avg_shot_mid = sum(midfielders) / len(midfielders)
    avg_shot_for = sum(forwards) / len(forwards)
    avg_shot_goal = sum(goalkeepers) / len(goalkeepers)
    return avg_shot_def, avg_shot_mid, avg_shot_for, avg_shot_goal


def max_GF_GA_ratio(teams_data):
    """Returns the string name of a team with highest ratio of goalsFor to
    goalsAgainst

    >>> max_GF_GA_ratio(teams_data)
    'Portugal'
    """
    dict_goals_ag = {}
    team_max_ratio = ''
    for team in teams_data:
        g_for = int(team['goalsFor'])  # to get goalsFor
        g_against = int(team['goalsAgainst'])  # to get goalsAgainst
        ratio = g_for / g_against  # to get ratio of goalsFor to goalsAgainst
        dict_goals_ag[f"{team['team']}"] = ratio  # add to dict_goals_ag
    team_name_list, ratio_list = list(dict_goals_ag.keys()), list(dict_goals_ag.values())
    max_ratio = max(ratio_list)  # to find max ratio in value dict list
    for i in range(len(dict_goals_ag)):
        if dict_goals_ag[f'{team_name_list[i]}'] == max_ratio:
            team_max_ratio = team_name_list[i]
    return team_max_ratio


def whose_player_list(players_data, teams_data):
    """Returns a list of tuples; each tuple has information about a player who
    is on a team ranked in the top 10, plays less than 250 minutes and makes
    more than 150 passes; the format for each tuple is (player's surname, team
    played for, team ranking, minutes played, number of passes)

    >>> whose_player_list(players_data, teams_data)
    [('Veron', 'Argentina', 7, 185, 235), ('Montolivo', 'Italy', 5, 236, 163)]
    """
    # Reminder: Convert minutes and passes to integers before comparing to values
    list_player = []
    for i in range(len(players_data)):
        surname = players_data[i]['surname']
        team = players_data[i]['team']
        minutes = int(players_data[i]['minutes'])
        passes = int(players_data[i]['passes'])
        ranking = 200
        for j in range(len(teams_data)):
            if teams_data[j]['team'] == team:
                ranking = int(teams_data[j]['ranking'])
        if (ranking <= 10) and (minutes <= 250) and (passes >= 150):
            list_player.append((surname, team, ranking, minutes, passes))
    return list_player


def team_list_shots_per_minute(players_data, teams_data):
    """Returns a list of tuples; each tuple has information about a team and
    its shots per minute value generated by its players

    Notes: the test results below are printed out with five decimal places to
    get around floating-point errors.

    >>> list_of_tuples = team_list_shots_per_minute(players_data, teams_data)
    >>> list_of_tuples.sort()
    >>> for team,shots in list_of_tuples:
    ...     print(f'{team} {shots:.5f}')
    ... 
    Algeria 0.01050
    Argentina 0.01394
    Australia 0.01010
    Brazil 0.01440
    Cameroon 0.01178
    Chile 0.01152
    Denmark 0.01077
    England 0.01237
    France 0.00998
    Germany 0.01121
    Ghana 0.01337
    Greece 0.01077
    Honduras 0.00438
    Italy 0.01212
    Ivory Coast 0.01313
    Japan 0.00886
    Mexico 0.01086
    Netherlands 0.01128
    New Zealand 0.00505
    Nigeria 0.00996
    North Korea 0.01077
    Paraguay 0.00928
    Portugal 0.01263
    Serbia 0.01286
    Slovakia 0.00884
    Slovenia 0.00572
    South Africa 0.01184
    South Korea 0.01111
    Spain 0.01380
    Switzerland 0.00721
    USA 0.01282
    Uruguay 0.01118
    """
    dict_total = {}
    for i in range(len(teams_data)):
        dict_total[teams_data[i]['team']] = [0, 0]  # to get [shots,minutes]
    for j in range(len(players_data)):
        teams = players_data[j]['team']
        shots = int(players_data[j]['shots'])
        minutes = int(players_data[j]['minutes'])
        teams_shot_min = dict_total[teams]
        teams_shot_min[0] += shots  # to plus how many shots in team
        teams_shot_min[1] += minutes  # to plus how many minutes in team
    final_list = []  # to get shots per minute value
    for name, num_list in dict_total.items():
        final_list.append((name, num_list[0] / num_list[1]))
    return final_list


if __name__ == "__main__":
    import doctest

    doctest.testmod()
